spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courseDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
        hibernate:
          format_sql: true
server:
  port: 8080
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
  logging:
    level:
      root: INFO